from fpdf import FPDF
import os

class MedicalReportPDF(FPDF):
    def header(self):
        # Logo placeholder or Clinic Name
        self.set_font('Arial', 'B', 16)
        self.cell(0, 10, 'MediConnect | Medical Report', 0, 1, 'C')
        self.ln(5)
        
        # Line break
        self.set_draw_color(14, 165, 233) # Primary Blue Color
        self.set_line_width(1)
        self.line(10, 25, 200, 25)
        self.ln(10)

    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.set_text_color(128)
        self.cell(0, 10, f'Generated by MediConnect AI - Page {self.page_no()}', 0, 0, 'C')

# UPDATED FUNCTION SIGNATURE TO INCLUDE follow_up_days
def generate_medical_report(patient_name, date_str, summary_json, doctor_notes, filename, follow_up_days=None):
    pdf = MedicalReportPDF()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)

    # 1. Patient Details
    pdf.set_font("Arial", "B", 12)
    pdf.cell(0, 10, f"Patient Name: {patient_name}", ln=True)
    pdf.cell(0, 10, f"Date: {date_str}", ln=True)
    pdf.ln(5)

    # 2. AI Summary Section
    if summary_json:
        pdf.set_fill_color(240, 249, 255) # Light Blue
        pdf.set_font("Arial", "B", 12)
        pdf.cell(0, 10, "Patient Summary (AI Triage)", 0, 1, 'L', fill=True)
        pdf.ln(2)
        
        pdf.set_font("Arial", "", 11)
        for key, value in summary_json.items():
            # Format Key
            clean_key = key.replace("_", " ").title()
            
            # Format Value (Handle lists or simple strings)
            clean_val = str(value)
            if isinstance(value, list):
                clean_val = ", ".join(value)
            
            pdf.multi_cell(0, 8, f"{clean_key}: {clean_val}")
        
        pdf.ln(5)

    # 3. Doctor's Response Section (The Prescription)
    pdf.set_fill_color(220, 252, 231) # Light Green
    pdf.set_font("Arial", "B", 12)
    pdf.cell(0, 10, "Doctor's Notes & Prescription", 0, 1, 'L', fill=True)
    pdf.ln(2)

    pdf.set_font("Arial", "", 11)
    pdf.multi_cell(0, 8, doctor_notes)
    
    # --- NEW FOLLOW-UP SECTION ---
    if follow_up_days:
        pdf.ln(5)
        pdf.set_font("Arial", "B", 11)
        pdf.set_text_color(220, 38, 38) # Red color for emphasis
        pdf.cell(0, 10, f"Follow-up Required: In {follow_up_days} Days", ln=True)
        pdf.set_text_color(0) # Reset to black
    # -----------------------------

    pdf.ln(20)
    
    # 4. Signature
    pdf.set_font("Arial", "I", 10)
    pdf.cell(0, 10, "Digitally Signed by Dr. ____________________", ln=True)

    # Save
    output_folder = "uploaded_files"
    os.makedirs(output_folder, exist_ok=True)
    file_path = os.path.join(output_folder, filename)
    pdf.output(file_path)
    
    return file_path